name: course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotlipy=0.7.0=py38h0a891b7_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=38.0.3=py38h80a4ca7_0
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.6.2=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-visual-tools=11.6.2=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=hca18f0e_0
  - gds-tools=1.4.0.31=0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.38=h753d276_0
  - libsqlite=3.39.4=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h55922b4_4
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.4=he0ac6c6_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - nsight-compute=2022.3.0.22=0
  - numpy=1.23.4=py38h7042d01_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.7=h166bdaf_0
  - pillow=9.2.0=py38h9eb91d8_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.13=ha86cf86_0_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.13.0=py3.8_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sqlite=3.39.4=h4ff8645_0
  - tbb=2021.6.0=h924138e_1
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.13.0=py38_cu116
  - torchvision=0.14.0=py38_cu116
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blis==0.7.9
    - catalogue==2.0.8
    - click==8.1.3
    - confection==0.0.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - cymem==2.0.7
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==1.2.0
    - fastai==2.7.10
    - fastcore==1.5.27
    - fastdownload==0.0.7
    - fastjsonschema==2.16.2
    - fastprogress==1.0.3
    - fonttools==4.38.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.0
    - jupyter-client==7.4.5
    - jupyter-core==5.0.0
    - jupyter-server==1.23.2
    - jupyterlab-pygments==0.2.2
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - murmurhash==1.0.9
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - packaging==21.3
    - pandas==1.5.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pathy==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - preshed==3.0.8
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.32
    - protobuf==4.21.9
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pydantic==1.10.2
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - pyzmq==24.0.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - send2trash==1.8.0
    - sentry-sdk==1.11.0
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - spacy==3.4.3
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.5
    - stack-data==0.6.1
    - terminado==0.17.0
    - thinc==8.1.5
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typer==0.7.0
    - wandb==0.13.5
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - zipp==3.10.0
prefix: /home/darek/mambaforge/envs/course
