method: bayes
metric:
  goal: maximize
  name: validation/mean_dice
parameters:
  model_dropout_prob:
    distribution: uniform
    max: 0.5
    min: 0.1
  model_init_filters:
    values:
      - 8
      - 16
      - 32
  initial_learning_rate:
    distribution: uniform
    max: 0.001
    min: 1e-06
  dice_loss_smoothen_denominator:
    distribution: uniform
    max: 0.0001
    min: 1e-06
  dice_loss_smoothen_numerator:
    distribution: uniform
    max: 0.0001
    min: 1e-06
  weight_decay:
    distribution: uniform
    max: 0.001
    min: 1e-06